import fs from "node:fs";
import path from "node:path";

function lcg(seed) {
  let state = seed >>> 0;
  return () => {
    state = (1664525 * state + 1013904223) >>> 0;
    return state / 2 ** 32;
  };
}

function fmt(x) {
  return Number.isFinite(x) ? x.toFixed(6) : String(x);
}

const rng = lcg(123456789);
const nRows = 200;

const header = ["x1", "x2", "x3", "x4", "y"];
const lines = [header.join(",")];

for (let i = 0; i < nRows; i++) {
  const x1 = -3 + 6 * rng();
  const x2 = -3 + 6 * rng();
  const x3 = -3 + 6 * rng();
  const x4 = -3 + 6 * rng();
  const y = x1 * x1 + 0.5 * x2 - (x3 * x4 * x4) / (x1 * x1 + 1.0);
  lines.push([fmt(x1), fmt(x2), fmt(x3), fmt(x4), fmt(y)].join(","));
}

const csv = lines.join("\n") + "\n";

const outPath = path.join(process.cwd(), "src", "generated", "defaultCsv.ts");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/generate_default_csv.mjs\n// Formula: y = x1^2 + 0.5*x2 - x3*x4^2/(x1^2 + 1.0)\n\nexport const DEFAULT_CSV: string = ${JSON.stringify(
    csv
  )};\n`
);

